# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Inteligência Superficial
description: Mergulhando de cabeça em inteligência artificial e machine learning
github_username: murilo-cunha
# you can comment the below line out if your repo name is not different than your baseurl
# github_repo: "blog-ia"

# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value. 
url: "https://murilo-cunha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/inteligencia-superficial" # the subpath of your site, e.g. "/blog".

# The avatar for the header - has to be "baseurl + image location"
avatar: "/inteligencia-superficial/images/avatar.png"

# Github and twitter are optional:
minima:
  social_links:
    github: murilo-cunha
    linkedin: murilo-cunha

# Set this to true to get LaTeX math equation support
use_math: True

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: true

# Set this to true to display tags on each post
show_tags: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: 

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  binder: true
  colab: true

# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
